name: buku_saku_2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.3

  #punya aplikasi
  flutter_staggered_grid_view: ^0.6.1
  pie_chart: ^5.3.1
  fluttertoast: ^8.0.8
  dropdown_search: ^5.0.2
  number_inc_dec: ^0.8.0
  intl: ^0.17.0

  #  manajemen file
  file_picker: ^4.5.1
  open_file: ^3.2.1
  path_provider: ^2.0.9
  pdfx: ^2.0.1+2
  syncfusion_flutter_xlsio: ^20.1.59-beta
  share_plus: ^4.0.10

  #back end
  sqflite: ^2.0.2
  provider: ^6.0.2
  get:
  get_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/introduction/
    - assets/icons/
    - assets/jsonfile/
    - assets/files/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf